### ISSUE TITLE
Local variable "i" for each model should be the first letter of the table

### ISSUE THREAD

**Issue by mrz1836** [jeffhoye/modelq#6]
This is opinionated...

But I prefer:

func (o *OrderReceipt) MyFunc {}

vs:

func (i *OrderReceipt) MyFunc {}

**Comment by jeffhoye** [comment]
Actually, it should be "r" since it's a Receipt.  What kind of Receipt?  An
Order Receipt.

I see "i" as an item, which is always correct.  But sure, one day we can
correct it.

**Comment by jeffhoye** [comment]
However, due to the template language, this will be a fair amount of
trouble and make the template unreadable/unmaintainable.  If we want more
automated methods, it's best to pick a variable name across all models for
auto-generated functions.

**Comment by mrz1836** [comment]
Yeah it's not a big deal, just looks weird when "i" i.Something and i'm expecting it to be context based off the model.
