### ISSUE TITLE
Run modelq on all models?

### ISSUE THREAD

**Issue by mrz1836** [jeffhoye/modelq#9]
Sometimes we need to run modelq again on all the models. Maybe there could be a way to detect all _mq files and run modelq on those models?

**Comment by jeffhoye** [comment]
sure

**Comment by jeffhoye** [comment]
oh, this sucks because of using nonstandard names: -name thing: restaurant => vendor

**Comment by mrz1836** [comment]
Very true, unless that data was stored in the _mq file - that could be parsed...?

**Comment by jeffhoye** [comment]
it is, but now it's a much harder problem

**Comment by mrz1836** [comment]
Ok - it's not a big issue.

**Comment by jeffhoye** [comment]
jesus fucking christ, it works
